config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get 'home/index'
  get '/login' ,to: 'sessions#new'
  post '/login',to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/signup', to:'users#new'
  post '/signup', to: 'users#create'
  resources :users, only: [:new, :create]
  resources :class_rooms
  get '/dashboard', to: 'dashboards#index'
  put 'add_student', to: 'class_rooms#add_student'
  put 'delete_student', to: 'class_rooms#delete_student'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/class_room.rb
class ClassRoom < ApplicationRecord
    has_and_belongs_to_many :users
    validates :name, presence: true
end

app/models/instructor.rb
class Instructor < User
    def self.model_name
        User.model_name
    end
end

app/models/registration.rb
class Registration < ApplicationRecord
  belongs_to :user
  belongs_to :class_room
end

app/models/student.rb
class Student < User
    def self.model_name
        User.model_name
    end
end

app/models/user.rb
class User < ApplicationRecord
    has_and_belongs_to_many :class_rooms
    has_secure_password
    validates :email, presence: true    
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include SessionsHelper
end

app/controllers/class_rooms_controller.rb
class ClassRoomsController < ApplicationController
    skip_before_action :verify_authenticity_token
    before_action :student_user, only: [:new, :create, :show, :destroy, :update]
    def new
        @class_room = ClassRoom.new
    end
    def create
        @class_room = ClassRoom.create(class_room_params)
        add_instructor if @class_room.save

    end
    def show
        @class_room = ClassRoom.find(params[:id])
        @unassigned_students = unassigned_students_query
        @class_room_students = class_room_students_query
        @class_room_instructor = current_user
    end
    def update
    end
    def destroy
        @class_room = ClassRoom.find(params[:id])
        @class_room.users.delete_all
        ClassRoom.delete(@class_room)
        redirect_to dashboard_path
    end
    def add_student
        @student = User.find(params[:student_id])
        @class_room = ClassRoom.find(params[:class_room_id])
        #for debug
        @class_room.users << @student 
        #render '/show' if @class_room.save
    end
    def delete_student
        @student = User.find(params[:student_id])
        @class_room = ClassRoom.find(params[:class_room_id])
        @class_room.users.delete(@student)
    end
    private
    def unassigned_students_query
        User.joins("LEFT JOIN class_rooms_users ON users.id = class_rooms_users.user_id")
            .where("class_room_id IS NULL and type ='Student' ")
    end

    def class_room_students_query
        User.joins("INNER JOIN class_rooms_users ON users.id = class_rooms_users.user_id")
        .where("type ='Student' and class_room_id = #{@class_room.id} ")
    end
    def add_instructor
        @instructor = current_user
        @class_room.users << @instructor
        redirect_to dashboard_path
    end
    def class_room_params
        params.require(:class_room).permit(:name)
    end
    def student_user
        @user = current_user
        
        if @user.type == "Student"
            flash[:danger] = "only Instructors can access class rooms"
            redirect_to dashboard_path 
        end
    end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
    before_action :logged_in_user, only: [:index]
    def index
        @user = current_user
        if @user.type == 'Student'
            student_dashboard
        else
            instructor_dashboard
        end
    end
    private
    def logged_in_user
        unless logged_in?
            flash[:danger] = "please log in."
            redirect_to login_path
        end
    end
    def student_dashboard
        # check if user.classrooms is empty or not 
        @class_room = @user.class_rooms.first if !@user.class_rooms.empty?
        render :student_dashboard
    end
    def instructor_dashboard
        @class_rooms = @user.class_rooms
        render :instructor_dashboard
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email])
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to dashboard_path
    else
      flash[:danger] = "Email or password is invalid"
      render "new"
    end
  end

  def destroy
    log_out
    redirect_to root_url, notice: "Logged out!"
  end
end

app/controllers/sign_up_controller.rb
class SignUpController < ApplicationController

end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        if @user.save
            log_in @user
            #flash[:success] = "Welcome #{@user.type} #{@user.email} to the class room portal app"
            redirect_to '/dashboard'
        else 
            render 'new'
        end
    end
    private
    def user_params
        params.require(:user).permit(:email, :password, :type)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/class_room_helper.rb
module ClassRoomHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/instructors_helper.rb
module InstructorsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def log_in(user)
        session[:user_id] = user.id
    end

    def current_user
        if session[:user_id]
            @current_user ||= User.find_by(id: session[:user_id])
        end
    end
    
    def logged_in?
        @current_user = current_user
        !@current_user.nil?
    end
    
    def log_out
        session.delete(:user_id)
        @current_user = nil
    end
end

app/helpers/sign_up_helper.rb
module SignUpHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/class_rooms/new.html.erb
<% provide(:title, 'Create Room') %>
<h1>Create Room</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@class_room) do |f| %>
      <%= f.label :name %>
      <%= f.text_field :name %>
      <%= f.submit "Create room", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/class_rooms/show.html.erb
<h1>
    <%= @class_room.name%>
</h1>
<h2> class room instructor</h2>
<p> 
    <%=@class_room_instructor.email%>
</p>
<h2> class room students </h2>
<ul>
    <% @class_room_students.each do |student|%>
        <li>
            <%= student.email%>
             <input type="button" value="unassign" onclick="delete_student(<%=student.id%>,
              <%=@class_room.id%>)">

        </li>
    <% end %>
</ul>
<h2> unassigned students </h2>
<ul>
    <% @unassigned_students.each do |student|%>
        <li>
            <%= student.email%>
            <input type="button" value="assign" onclick="add_student(<%=student.id%>, <%=@class_room.id%>)">
        </li>
    <% end %>
</ul>


<h2>
    <%= link_to "Delete", class_room_path, method: :delete  %>
</h2>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= f.label :email %>
      <%= f.email_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :type %>
      <%= f.select :type, ['Student', 'Instructor']%>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% if @user.type == "Student"%>
    <% if @user.class_rooms.empty?%>
        <h2> you're not enorlled in any class yet <h2>
    <% else %>
        <table>
            <thead>
                <tr >
                <th>Class Name </th>
                <th>Class Admin</th>
                <th colspan="10"></th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td><%= @myClassRoom.first.name %></td>
                    <td><%= @classRoomInstructor.email %></td>
                </tr>
            </tbody>
    </table>
    <% end %>
<% end %>
<% if @user.type == 'Instructor'%>
    <h1> your class rooms  </h1>
    <ul>
        <% @myClassRoom.each do |classRoom| %>
            <li>
                <%= link_to classRoom.name, classRoom%>
            </li>
        <%end%>
    </ul>
    <h2> students </h2>
    <table>
  <thead>
    <tr>
      <th>Email</th>
      <th></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @notAssignedStudent.each do |student| %>
      <tr>
        <td><%= student.email %></td>
        <td><%= link_to 'assign'  %></td>
      </tr>
    <% end %>
  </tbody>
</table>
    
<%end%>